name: Close Blank Issues
on:
  issues:
    types:
      - reopened
      - opened
      - edited

jobs:
  close-empty-issues:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Run empty issues closer
        uses: rickstaa/empty-issues-closer-action@v1
        with:
          github_token: ${{ secrets.GH_ISSUES_TOKEN }}
          check_templates: true
