name: Dotnet Format

on:
  workflow_dispatch:
  push:
    branches:
      - main
    paths:
      - BinDays.Api/**
      - BinDays.Api.Collectors/**
  pull_request:
    paths:
      - BinDays.Api/**
      - BinDays.Api.Collectors/**

jobs:
  dotnet_format:
    name: Dotnet Format
    runs-on: ubuntu-latest
    env:
      WORKFLOW_TOKEN: ${{ secrets.WORKFLOW_TOKEN }}

    steps:
      - name: Checkout code
        uses: actions/checkout@v4
        with:
          ref: ${{ github.head_ref }}
          token: ${{ secrets.WORKFLOW_TOKEN || secrets.GITHUB_TOKEN }}

      - name: Setup .NET
        uses: actions/setup-dotnet@v4
        with:
          dotnet-version: "8.0.x"

      - name: Format code
        if: env.WORKFLOW_TOKEN != ''
        run: dotnet format --no-restore --severity info

      - name: Commit changes
        if: env.WORKFLOW_TOKEN != ''
        run: |
          git config --global user.email "actions@github.com"
          git config --global user.name "GitHub Action"
          git add .
          git diff-index --quiet HEAD -- || (
            git commit -am "Auto-format code with dotnet format"
            git push
          )

      - name: Verify formatting
        if: env.WORKFLOW_TOKEN == ''
        run: dotnet format --no-restore --verify-no-changes --severity info
